package com.bempel.perf.pmuevents;

import java.util.*;
import java.util.function.Consumer;

public class Silvermont implements PMUEventMap {
    private  final Map<String, PMUEvent> eventMap = new HashMap<>();

    static {
        PMUEvents.register(new Silvermont());
    }

    {
		eventMap.put("L2_REJECT_XQ.ALL", new PMUEvent("This event counts the number of demand and prefetch transactions that the L2 XQ rejects due to a full or near full condition which likely indicates back pressure from the IDI link. The XQ may reject transactions from the L2Q (non-cacheable requests), BBS (L2 misses) and WOB (L2 write-back victims).", "0x30", "0,1", "0x0", "L2_REJECT_XQ.ALL", "200003", "Counts the number of request from the L2 that were not accepted into the XQ", null));
		eventMap.put("CORE_REJECT_L2Q.ALL", new PMUEvent("Counts the number of (demand and L1 prefetchers) core requests rejected by the L2Q due to a full or nearly full w condition which likely indicates back pressure from L2Q.  It also counts requests that would have gone directly to the XQ, but are rejected due to a full or nearly full condition, indicating back pressure from the IDI link.  The L2Q may also reject transactions  from a core to insure fairness between cores, or to delay a core?s dirty eviction when the address conflicts incoming external snoops.  (Note that L2 prefetcher requests that are dropped are not counted by this event.)", "0x31", "0,1", "0x0", "CORE_REJECT_L2Q.ALL", "200003", "Counts the number of request that were not accepted into the L2Q because the L2Q is FULL.", null));
		eventMap.put("LONGEST_LAT_CACHE.REFERENCE", new PMUEvent("This event counts requests originating from the core that references a cache line in the L2 cache.", "0x2E", "0,1", "0x4f", "LONGEST_LAT_CACHE.REFERENCE", "200003", "L2 cache requests from this core", null));
		eventMap.put("LONGEST_LAT_CACHE.MISS", new PMUEvent("This event counts the total number of L2 cache references and the number of L2 cache misses respectively.", "0x2E", "0,1", "0x41", "LONGEST_LAT_CACHE.MISS", "200003", "L2 cache request misses", null));
		eventMap.put("FETCH_STALL.ICACHE_FILL_PENDING_CYCLES", new PMUEvent("Counts cycles that fetch is stalled due to an outstanding ICache miss. That is, the decoder queue is able to accept bytes, but the fetch unit is unable to provide bytes due to an ICache miss.  Note: this event is not the same as the total number of cycles spent retrieving instruction cache lines from the memory hierarchy.Counts cycles that fetch is stalled due to any reason. That is, the decoder queue is able to accept bytes, but the fetch unit is unable to provide bytes.  This will include cycles due to an ITLB miss, ICache miss and other events. ", "0x86", "0,1", "0x4", "FETCH_STALL.ICACHE_FILL_PENDING_CYCLES", "200003", "Cycles code-fetch stalled due to an outstanding ICache miss.", null));
		eventMap.put("REHABQ.LD_BLOCK_ST_FORWARD", new PMUEvent("This event counts the number of retired loads that were prohibited from receiving forwarded data from the store because of address mismatch.", "0x03", "0,1", "0x1", "REHABQ.LD_BLOCK_ST_FORWARD", "200003", "Loads blocked due to store forward restriction", null));
		eventMap.put("REHABQ.LD_BLOCK_STD_NOTREADY", new PMUEvent("This event counts the cases where a forward was technically possible, but did not occur because the store data was not available at the right time.", "0x03", "0,1", "0x2", "REHABQ.LD_BLOCK_STD_NOTREADY", "200003", "Loads blocked due to store data not ready", null));
		eventMap.put("REHABQ.ST_SPLITS", new PMUEvent("This event counts the number of retire stores that experienced cache line boundary splits.", "0x03", "0,1", "0x4", "REHABQ.ST_SPLITS", "200003", "Store uops that split cache line boundary", null));
		eventMap.put("REHABQ.LD_SPLITS", new PMUEvent("This event counts the number of retire loads that experienced cache line boundary splits.", "0x03", "0,1", "0x8", "REHABQ.LD_SPLITS", "200003", "Load uops that split cache line boundary", null));
		eventMap.put("REHABQ.LOCK", new PMUEvent("This event counts the number of retired memory operations with lock semantics. These are either implicit locked instructions such as the XCHG instruction or instructions with an explicit LOCK prefix (0xF0).", "0x03", "0,1", "0x10", "REHABQ.LOCK", "200003", "Uops with lock semantics", null));
		eventMap.put("REHABQ.STA_FULL", new PMUEvent("This event counts the number of retired stores that are delayed because there is not a store address buffer available.", "0x03", "0,1", "0x20", "REHABQ.STA_FULL", "200003", "Store address buffer full", null));
		eventMap.put("REHABQ.ANY_LD", new PMUEvent("This event counts the number of load uops reissued from Rehabq.", "0x03", "0,1", "0x40", "REHABQ.ANY_LD", "200003", "Any reissued load uops", null));
		eventMap.put("REHABQ.ANY_ST", new PMUEvent("This event counts the number of store uops reissued from Rehabq.", "0x03", "0,1", "0x80", "REHABQ.ANY_ST", "200003", "Any reissued store uops", null));
		eventMap.put("MEM_UOPS_RETIRED.L1_MISS_LOADS", new PMUEvent("This event counts the number of load ops retired that miss in L1 Data cache. Note that prefetch misses will not be counted.", "0x04", "0,1", "0x1", "MEM_UOPS_RETIRED.L1_MISS_LOADS", "200003", "Loads missed L1", null));
		eventMap.put("MEM_UOPS_RETIRED.L2_HIT_LOADS", new PMUEvent("This event counts the number of load ops retired that hit in the L2.", "0x04", "0,1", "0x2", "MEM_UOPS_RETIRED.L2_HIT_LOADS", "200003", "Loads hit L2", null));
		eventMap.put("MEM_UOPS_RETIRED.L2_MISS_LOADS", new PMUEvent("This event counts the number of load ops retired that miss in the L2.", "0x04", "0,1", "0x4", "MEM_UOPS_RETIRED.L2_MISS_LOADS", "100007", "Loads missed L2", null));
		eventMap.put("MEM_UOPS_RETIRED.UTLB_MISS", new PMUEvent("This event counts the number of load ops retired that had UTLB miss.", "0x04", "0,1", "0x10", "MEM_UOPS_RETIRED.UTLB_MISS", "200003", "Loads missed UTLB", null));
		eventMap.put("MEM_UOPS_RETIRED.HITM", new PMUEvent("This event counts the number of load ops retired that got data from the other core or from the other module.", "0x04", "0,1", "0x20", "MEM_UOPS_RETIRED.HITM", "200003", "Cross core or cross module hitm", null));
		eventMap.put("MEM_UOPS_RETIRED.ALL_LOADS", new PMUEvent("This event counts the number of load ops retired.", "0x04", "0,1", "0x40", "MEM_UOPS_RETIRED.ALL_LOADS", "200003", "All Loads", null));
		eventMap.put("MEM_UOPS_RETIRED.ALL_STORES", new PMUEvent("This event counts the number of store ops retired.", "0x04", "0,1", "0x80", "MEM_UOPS_RETIRED.ALL_STORES", "200003", "All Stores", null));
		eventMap.put("OFFCORE_RESPONSE", new PMUEvent("Offcore response can be programmed only with a specific pair of event select and counter MSR, and with specific event codes and predefine mask bit value in a dedicated MSR to specify attributes of the offcore transaction.", "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE", "100007", "Offcore response can be programmed only with a specific pair of event select and counter MSR, and with specific event codes and predefine mask bit value in a dedicated MSR to specify attributes of the offcore transaction", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_CODE_RD.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_CODE_RD.L2_MISS.ANY", "100007", "Counts any code reads (demand & prefetch) that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_CODE_RD.L2_MISS.HITM_OTHER_CORE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_CODE_RD.L2_MISS.HITM_OTHER_CORE", "100007", "Counts any code reads (demand & prefetch) that hit in the other module where modified copies were found in other core's L1 cache.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_CODE_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_CODE_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts any code reads (demand & prefetch) that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_CODE_RD.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_CODE_RD.L2_MISS.SNOOP_MISS", "100007", "Counts any code reads (demand & prefetch) that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_CODE_RD.ANY_RESPONSE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_CODE_RD.ANY_RESPONSE", "100007", "Counts any code reads (demand & prefetch) that have any response type.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_RFO.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_RFO.L2_MISS.ANY", "100007", "Counts any rfo reads (demand & prefetch) that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_RFO.L2_MISS.HITM_OTHER_CORE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_RFO.L2_MISS.HITM_OTHER_CORE", "100007", "Counts any rfo reads (demand & prefetch) that hit in the other module where modified copies were found in other core's L1 cache.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_RFO.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_RFO.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts any rfo reads (demand & prefetch) that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_RFO.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_RFO.L2_MISS.SNOOP_MISS", "100007", "Counts any rfo reads (demand & prefetch) that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_RFO.ANY_RESPONSE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_RFO.ANY_RESPONSE", "100007", "Counts any rfo reads (demand & prefetch) that have any response type.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_DATA_RD.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_DATA_RD.L2_MISS.ANY", "100007", "Counts any data read (demand & prefetch) that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_DATA_RD.L2_MISS.HITM_OTHER_CORE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_DATA_RD.L2_MISS.HITM_OTHER_CORE", "100007", "Counts any data read (demand & prefetch) that hit in the other module where modified copies were found in other core's L1 cache.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_DATA_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_DATA_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts any data read (demand & prefetch) that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_DATA_RD.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_DATA_RD.L2_MISS.SNOOP_MISS", "100007", "Counts any data read (demand & prefetch) that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_DATA_RD.ANY_RESPONSE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_DATA_RD.ANY_RESPONSE", "100007", "Counts any data read (demand & prefetch) that have any response type.", null));
		eventMap.put("OFFCORE_RESPONSE.STREAMING_STORES.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.STREAMING_STORES.L2_MISS.ANY", "100007", "Counts streaming store that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_REQUEST.L2_MISS.HITM_OTHER_CORE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_REQUEST.L2_MISS.HITM_OTHER_CORE", "100007", "Counts any request that hit in the other module where modified copies were found in other core's L1 cache.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_REQUEST.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_REQUEST.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts any request that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_REQUEST.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_REQUEST.L2_MISS.SNOOP_MISS", "100007", "Counts any request that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.ANY_REQUEST.ANY_RESPONSE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.ANY_REQUEST.ANY_RESPONSE", "100007", "Counts any request that have any response type.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L1_DATA_RD.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L1_DATA_RD.L2_MISS.ANY", "100007", "Counts DCU hardware prefetcher data read that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L1_DATA_RD.L2_MISS.HITM_OTHER_CORE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L1_DATA_RD.L2_MISS.HITM_OTHER_CORE", "100007", "Counts DCU hardware prefetcher data read that hit in the other module where modified copies were found in other core's L1 cache.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L1_DATA_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L1_DATA_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts DCU hardware prefetcher data read that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L1_DATA_RD.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L1_DATA_RD.L2_MISS.SNOOP_MISS", "100007", "Counts DCU hardware prefetcher data read that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L1_DATA_RD.ANY_RESPONSE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L1_DATA_RD.ANY_RESPONSE", "100007", "Counts DCU hardware prefetcher data read that have any response type.", null));
		eventMap.put("OFFCORE_RESPONSE.PARTIAL_WRITES.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PARTIAL_WRITES.L2_MISS.ANY", "100007", "Countsof demand RFO requests to write to partial cache lines that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.PARTIAL_READS.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PARTIAL_READS.L2_MISS.ANY", "100007", "Counts demand reads of partial cache lines (including UC and WC) that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_CODE_RD.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_CODE_RD.L2_MISS.ANY", "100007", "Counts code reads generated by L2 prefetchers that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_CODE_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_CODE_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts code reads generated by L2 prefetchers that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_CODE_RD.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_CODE_RD.L2_MISS.SNOOP_MISS", "100007", "Counts code reads generated by L2 prefetchers that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_RFO.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_RFO.L2_MISS.ANY", "100007", "Counts RFO requests generated by L2 prefetchers that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_RFO.L2_MISS.HITM_OTHER_CORE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_RFO.L2_MISS.HITM_OTHER_CORE", "100007", "Counts RFO requests generated by L2 prefetchers that hit in the other module where modified copies were found in other core's L1 cache.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_RFO.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_RFO.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts RFO requests generated by L2 prefetchers that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_RFO.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_RFO.L2_MISS.SNOOP_MISS", "100007", "Counts RFO requests generated by L2 prefetchers that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_DATA_RD.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_DATA_RD.L2_MISS.ANY", "100007", "Counts data cacheline reads generated by L2 prefetchers that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_DATA_RD.L2_MISS.HITM_OTHER_CORE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_DATA_RD.L2_MISS.HITM_OTHER_CORE", "100007", "Counts data cacheline reads generated by L2 prefetchers that hit in the other module where modified copies were found in other core's L1 cache.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_DATA_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_DATA_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts data cacheline reads generated by L2 prefetchers that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.PF_L2_DATA_RD.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.PF_L2_DATA_RD.L2_MISS.SNOOP_MISS", "100007", "Counts data cacheline reads generated by L2 prefetchers that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.COREWB.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.COREWB.L2_MISS.ANY", "100007", "Counts writeback (modified to exclusive) that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.COREWB.L2_MISS.NO_SNOOP_NEEDED", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.COREWB.L2_MISS.NO_SNOOP_NEEDED", "100007", "Counts writeback (modified to exclusive) that miss L2 with no details on snoop-related information.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_CODE_RD.OUTSTANDING", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_CODE_RD.OUTSTANDING", "100007", "Counts demand and DCU prefetch instruction cacheline that are are outstanding, per cycle, from the time of the L2 miss to when any response is received.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_CODE_RD.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_CODE_RD.L2_MISS.ANY", "100007", "Counts demand and DCU prefetch instruction cacheline that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_CODE_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_CODE_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts demand and DCU prefetch instruction cacheline that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_CODE_RD.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_CODE_RD.L2_MISS.SNOOP_MISS", "100007", "Counts demand and DCU prefetch instruction cacheline that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_CODE_RD.ANY_RESPONSE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_CODE_RD.ANY_RESPONSE", "100007", "Counts demand and DCU prefetch instruction cacheline that have any response type.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_RFO.OUTSTANDING", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_RFO.OUTSTANDING", "100007", "Counts demand and DCU prefetch RFOs that are are outstanding, per cycle, from the time of the L2 miss to when any response is received.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_RFO.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_RFO.L2_MISS.ANY", "100007", "Counts demand and DCU prefetch RFOs that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_RFO.L2_MISS.HITM_OTHER_CORE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_RFO.L2_MISS.HITM_OTHER_CORE", "100007", "Counts demand and DCU prefetch RFOs that hit in the other module where modified copies were found in other core's L1 cache.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_RFO.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_RFO.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts demand and DCU prefetch RFOs that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_RFO.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_RFO.L2_MISS.SNOOP_MISS", "100007", "Counts demand and DCU prefetch RFOs that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_DATA_RD.OUTSTANDING", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_DATA_RD.OUTSTANDING", "100007", "Counts demand and DCU prefetch data read that are are outstanding, per cycle, from the time of the L2 miss to when any response is received.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_DATA_RD.L2_MISS.ANY", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_DATA_RD.L2_MISS.ANY", "100007", "Counts demand and DCU prefetch data read that miss L2.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_DATA_RD.L2_MISS.HITM_OTHER_CORE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_DATA_RD.L2_MISS.HITM_OTHER_CORE", "100007", "Counts demand and DCU prefetch data read that hit in the other module where modified copies were found in other core's L1 cache.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_DATA_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_DATA_RD.L2_MISS.HIT_OTHER_CORE_NO_FWD", "100007", "Counts demand and DCU prefetch data read that miss L2 and the snoops to sibling cores hit in either E/S state and the line is not forwarded.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_DATA_RD.L2_MISS.SNOOP_MISS", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_DATA_RD.L2_MISS.SNOOP_MISS", "100007", "Counts demand and DCU prefetch data read that miss L2 with a snoop miss response.", null));
		eventMap.put("OFFCORE_RESPONSE.DEMAND_DATA_RD.ANY_RESPONSE", new PMUEvent(null, "0xB7", "0,1", "0x1", "OFFCORE_RESPONSE.DEMAND_DATA_RD.ANY_RESPONSE", "100007", "Counts demand and DCU prefetch data read that have any response type.", null));
		eventMap.put("ICACHE.ACCESSES", new PMUEvent("This event counts all instruction fetches, not including most uncacheablefetches.", "0x80", "0,1", "0x3", "ICACHE.ACCESSES", "200003", "Instruction fetches", null));
		eventMap.put("ICACHE.HIT", new PMUEvent("This event counts all instruction fetches from the instruction cache.", "0x80", "0,1", "0x1", "ICACHE.HIT", "200003", "Instruction fetches from Icache", null));
		eventMap.put("ICACHE.MISSES", new PMUEvent("This event counts all instruction fetches that miss the Instruction cache or produce memory requests. This includes uncacheable fetches. An instruction fetch miss is counted only once and not once for every cycle it is outstanding.", "0x80", "0,1", "0x2", "ICACHE.MISSES", "200003", "Icache miss", null));
		eventMap.put("MS_DECODED.MS_ENTRY", new PMUEvent("Counts the number of times the MSROM starts a flow of UOPS. It does not count every time a UOP is read from the microcode ROM.  The most common case that this counts is when a micro-coded instruction is encountered by the front end of the machine.  Other cases include when an instruction encounters a fault, trap, or microcode assist of any sort.  The event will count MSROM startups for UOPS that are speculative, and subsequently cleared by branch mispredict or machine clear.  Background: UOPS are produced by two mechanisms.  Either they are generated by hardware that decodes instructions into UOPS, or they are delivered by a ROM (called the MSROM) that holds UOPS associated with a specific instruction.  MSROM UOPS might also be delivered in response to some condition such as a fault or other exceptional condition.  This event is an excellent mechanism for detecting instructions that require the use of MSROM instructions.", "0xE7", "0,1", "0x1", "MS_DECODED.MS_ENTRY", "200003", "Counts the number of times entered into a ucode flow in the FEC.  Includes inserted flows due to front-end detected faults or assists.  Speculative count.", null));
		eventMap.put("DECODE_RESTRICTION.PREDECODE_WRONG", new PMUEvent("Counts the number of times a decode restriction reduced the decode throughput due to wrong instruction length prediction.", "0xE9", "0,1", "0x1", "DECODE_RESTRICTION.PREDECODE_WRONG", "200003", "Counts the number of times a decode restriction reduced the decode throughput due to wrong instruction length prediction", null));
		eventMap.put("MACHINE_CLEARS.MEMORY_ORDERING", new PMUEvent("This event counts the number of times that pipeline was cleared due to memory ordering issues.", "0xC3", "0,1", "0x2", "MACHINE_CLEARS.MEMORY_ORDERING", "200003", "Stalls due to Memory ordering", null));
		eventMap.put("BR_INST_RETIRED.ALL_BRANCHES", new PMUEvent("ALL_BRANCHES counts the number of any branch instructions retired.  Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0x0", "BR_INST_RETIRED.ALL_BRANCHES", "200003", "Counts the number of branch instructions retired...", null));
		eventMap.put("BR_INST_RETIRED.JCC", new PMUEvent("JCC counts the number of conditional branch (JCC) instructions retired. Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0x7e", "BR_INST_RETIRED.JCC", "200003", "Counts the number of JCC branch instructions retired", null));
		eventMap.put("BR_INST_RETIRED.TAKEN_JCC", new PMUEvent("TAKEN_JCC counts the number of taken conditional branch (JCC) instructions retired. Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0xfe", "BR_INST_RETIRED.TAKEN_JCC", "200003", "Counts the number of taken JCC branch instructions retired", null));
		eventMap.put("BR_INST_RETIRED.CALL", new PMUEvent("CALL counts the number of near CALL branch instructions retired.  Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0xf9", "BR_INST_RETIRED.CALL", "200003", "Counts the number of near CALL branch instructions retired", null));
		eventMap.put("BR_INST_RETIRED.REL_CALL", new PMUEvent("REL_CALL counts the number of near relative CALL branch instructions retired.  Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0xfd", "BR_INST_RETIRED.REL_CALL", "200003", "Counts the number of near relative CALL branch instructions retired", null));
		eventMap.put("BR_INST_RETIRED.IND_CALL", new PMUEvent("IND_CALL counts the number of near indirect CALL branch instructions retired.  Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0xfb", "BR_INST_RETIRED.IND_CALL", "200003", "Counts the number of near indirect CALL branch instructions retired", null));
		eventMap.put("BR_INST_RETIRED.RETURN", new PMUEvent("RETURN counts the number of near RET branch instructions retired.  Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0xf7", "BR_INST_RETIRED.RETURN", "200003", "Counts the number of near RET branch instructions retired", null));
		eventMap.put("BR_INST_RETIRED.NON_RETURN_IND", new PMUEvent("NON_RETURN_IND counts the number of near indirect JMP and near indirect CALL branch instructions retired.  Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0xeb", "BR_INST_RETIRED.NON_RETURN_IND", "200003", "Counts the number of near indirect JMP and near indirect CALL branch instructions retired", null));
		eventMap.put("BR_INST_RETIRED.FAR_BRANCH", new PMUEvent("FAR counts the number of far branch instructions retired.  Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0xbf", "BR_INST_RETIRED.FAR_BRANCH", "200003", "Counts the number of far branch instructions retired", null));
		eventMap.put("BR_MISP_RETIRED.ALL_BRANCHES", new PMUEvent("ALL_BRANCHES counts the number of any mispredicted branch instructions retired. This umask is an architecturally defined event. This event counts the number of retired branch instructions that were mispredicted by the processor, categorized by type. A branch misprediction occurs when the processor predicts that the branch would be taken, but it is not, or vice-versa.  When the misprediction is discovered, all the instructions executed in the wrong (speculative) path must be discarded, and the processor must start fetching from the correct path.", "0xC5", "0,1", "0x0", "BR_MISP_RETIRED.ALL_BRANCHES", "200003", "Counts the number of mispredicted branch instructions retired", null));
		eventMap.put("BR_MISP_RETIRED.JCC", new PMUEvent("JCC counts the number of mispredicted conditional branches (JCC) instructions retired.  This event counts the number of retired branch instructions that were mispredicted by the processor, categorized by type. A branch misprediction occurs when the processor predicts that the branch would be taken, but it is not, or vice-versa.  When the misprediction is discovered, all the instructions executed in the wrong (speculative) path must be discarded, and the processor must start fetching from the correct path.", "0xC5", "0,1", "0x7e", "BR_MISP_RETIRED.JCC", "200003", "Counts the number of mispredicted JCC branch instructions retired", null));
		eventMap.put("BR_MISP_RETIRED.TAKEN_JCC", new PMUEvent("TAKEN_JCC counts the number of mispredicted taken conditional branch (JCC) instructions retired.  This event counts the number of retired branch instructions that were mispredicted by the processor, categorized by type. A branch misprediction occurs when the processor predicts that the branch would be taken, but it is not, or vice-versa.  When the misprediction is discovered, all the instructions executed in the wrong (speculative) path must be discarded, and the processor must start fetching from the correct path.", "0xC5", "0,1", "0xfe", "BR_MISP_RETIRED.TAKEN_JCC", "200003", "Counts the number of mispredicted taken JCC branch instructions retired", null));
		eventMap.put("BR_MISP_RETIRED.IND_CALL", new PMUEvent("IND_CALL counts the number of mispredicted near indirect CALL branch instructions retired.  This event counts the number of retired branch instructions that were mispredicted by the processor, categorized by type. A branch misprediction occurs when the processor predicts that the branch would be taken, but it is not, or vice-versa.  When the misprediction is discovered, all the instructions executed in the wrong (speculative) path must be discarded, and the processor must start fetching from the correct path.", "0xC5", "0,1", "0xfb", "BR_MISP_RETIRED.IND_CALL", "200003", "Counts the number of mispredicted near indirect CALL branch instructions retired", null));
		eventMap.put("BR_MISP_RETIRED.RETURN", new PMUEvent("RETURN counts the number of mispredicted near RET branch instructions retired.  This event counts the number of retired branch instructions that were mispredicted by the processor, categorized by type. A branch misprediction occurs when the processor predicts that the branch would be taken, but it is not, or vice-versa.  When the misprediction is discovered, all the instructions executed in the wrong (speculative) path must be discarded, and the processor must start fetching from the correct path.", "0xC5", "0,1", "0xf7", "BR_MISP_RETIRED.RETURN", "200003", "Counts the number of mispredicted near RET branch instructions retired", null));
		eventMap.put("BR_MISP_RETIRED.NON_RETURN_IND", new PMUEvent("NON_RETURN_IND counts the number of mispredicted near indirect JMP and near indirect CALL branch instructions retired.  This event counts the number of retired branch instructions that were mispredicted by the processor, categorized by type. A branch misprediction occurs when the processor predicts that the branch would be taken, but it is not, or vice-versa.  When the misprediction is discovered, all the instructions executed in the wrong (speculative) path must be discarded, and the processor must start fetching from the correct path.", "0xC5", "0,1", "0xeb", "BR_MISP_RETIRED.NON_RETURN_IND", "200003", "Counts the number of mispredicted near indirect JMP and near indirect CALL branch instructions retired", null));
		eventMap.put("UOPS_RETIRED.MS", new PMUEvent("This event counts the number of micro-ops retired that were supplied from MSROM.", "0xC2", "0,1", "0x1", "UOPS_RETIRED.MS", "2000003", "MSROM micro-ops retired", null));
		eventMap.put("UOPS_RETIRED.ALL", new PMUEvent("This event counts the number of micro-ops retired. The processor decodes complex macro instructions into a sequence of simpler micro-ops. Most instructions are composed of one or two micro-ops. Some instructions are decoded into longer sequences such as repeat instructions, floating point transcendental instructions, and assists. In some cases micro-op sequences are fused or whole instructions are fused into one micro-op. See other UOPS_RETIRED events for differentiating retired fused and non-fused micro-ops.", "0xC2", "0,1", "0x10", "UOPS_RETIRED.ALL", "2000003", "Micro-ops retired", null));
		eventMap.put("MACHINE_CLEARS.SMC", new PMUEvent("This event counts the number of times that a program writes to a code section. Self-modifying code causes a severe penalty in all Intel? architecture processors.", "0xC3", "0,1", "0x1", "MACHINE_CLEARS.SMC", "200003", "Self-Modifying Code detected", null));
		eventMap.put("MACHINE_CLEARS.FP_ASSIST", new PMUEvent("This event counts the number of times that pipeline stalled due to FP operations needing assists.", "0xC3", "0,1", "0x4", "MACHINE_CLEARS.FP_ASSIST", "200003", "Stalls due to FP assists", null));
		eventMap.put("MACHINE_CLEARS.ALL", new PMUEvent("Machine clears happen when something happens in the machine that causes the hardware to need to take special care to get the right answer. When such a condition is signaled on an instruction, the front end of the machine is notified that it must restart, so no more instructions will be decoded from the current path.  All instructions \"older\" than this one will be allowed to finish.  This instruction and all \"younger\" instructions must be cleared, since they must not be allowed to complete.  Essentially, the hardware waits until the problematic instruction is the oldest instruction in the machine.  This means all older instructions are retired, and all pending stores (from older instructions) are completed.  Then the new path of instructions from the front end are allowed to start into the machine.  There are many conditions that might cause a machine clear (including the receipt of an interrupt, or a trap or a fault).  All those conditions (including but not limited to MACHINE_CLEARS.MEMORY_ORDERING, MACHINE_CLEARS.SMC, and MACHINE_CLEARS.FP_ASSIST) are captured in the ANY event. In addition, some conditions can be specifically counted (i.e. SMC, MEMORY_ORDERING, FP_ASSIST).  However, the sum of SMC, MEMORY_ORDERING, and FP_ASSIST machine clears will not necessarily equal the number of ANY.", "0xC3", "0,1", "0x8", "MACHINE_CLEARS.ALL", "200003", "Counts all machine clears", null));
		eventMap.put("NO_ALLOC_CYCLES.ROB_FULL", new PMUEvent("Counts the number of cycles when no uops are allocated and the ROB is full (less than 2 entries available).", "0xCA", "0,1", "0x1", "NO_ALLOC_CYCLES.ROB_FULL", "200003", "Counts the number of cycles when no uops are allocated and the ROB is full (less than 2 entries available)", null));
		eventMap.put("NO_ALLOC_CYCLES.MISPREDICTS", new PMUEvent("Counts the number of cycles when no uops are allocated and the alloc pipe is stalled waiting for a mispredicted jump to retire.  After the misprediction is detected, the front end will start immediately but the allocate pipe stalls until the mispredicted.", "0xCA", "0,1", "0x4", "NO_ALLOC_CYCLES.MISPREDICTS", "200003", "Counts the number of cycles when no uops are allocated and the alloc pipe is stalled waiting for a mispredicted jump to retire.  After the misprediction is detected, the front end will start immediately but the allocate pipe stalls until the mispredicted ", null));
		eventMap.put("NO_ALLOC_CYCLES.RAT_STALL", new PMUEvent(null, "0xCA", "0,1", "0x20", "NO_ALLOC_CYCLES.RAT_STALL", "200003", "Counts the number of cycles when no uops are allocated and a RATstall is asserted.", null));
		eventMap.put("NO_ALLOC_CYCLES.NOT_DELIVERED", new PMUEvent("The NO_ALLOC_CYCLES.NOT_DELIVERED event is used to measure front-end inefficiencies, i.e. when front-end of the machine is not delivering micro-ops to the back-end and the back-end is not stalled. This event can be used to identify if the machine is truly front-end bound.  When this event occurs, it is an indication that the front-end of the machine is operating at less than its theoretical peak performance.  Background: We can think of the processor pipeline as being divided into 2 broader parts: Front-end and Back-end. Front-end is responsible for fetching the instruction, decoding into micro-ops (uops) in machine understandable format and putting them into a micro-op queue to be consumed by back end. The back-end then takes these micro-ops, allocates the required resources.  When all resources are ready, micro-ops are executed. If the back-end is not ready to accept micro-ops from the front-end, then we do not want to count these as front-end bottlenecks.  However, whenever we have bottlenecks in the back-end, we will have allocation unit stalls and eventually forcing the front-end to wait until the back-end is ready to receive more UOPS. This event counts the cycles only when back-end is requesting more uops and front-end is not able to provide them. Some examples of conditions that cause front-end efficiencies are: Icache misses, ITLB misses, and decoder restrictions that limit the the front-end bandwidth.", "0xCA", "0,1", "0x50", "NO_ALLOC_CYCLES.NOT_DELIVERED", "200003", "Counts the number of cycles when no uops are allocated, the IQ is empty, and no other condition is blocking allocation.", null));
		eventMap.put("NO_ALLOC_CYCLES.ALL", new PMUEvent("The NO_ALLOC_CYCLES.ALL event counts the number of cycles when the front-end does not provide any instructions to be allocated for any reason. This event indicates the cycles where an allocation stalls occurs, and no UOPS are allocated in that cycle.", "0xCA", "0,1", "0x3f", "NO_ALLOC_CYCLES.ALL", "200003", "Counts the number of cycles when no uops are allocated for any reason.", null));
		eventMap.put("RS_FULL_STALL.MEC", new PMUEvent("Counts the number of cycles and allocation pipeline is stalled and is waiting for a free MEC reservation station entry.  The cycles should be appropriately counted in case of the cracked ops e.g. In case of a cracked load-op, the load portion is sent to M.", "0xCB", "0,1", "0x1", "RS_FULL_STALL.MEC", "200003", "Counts the number of cycles and allocation pipeline is stalled and is waiting for a free MEC reservation station entry.  The cycles should be appropriately counted in case of the cracked ops e.g. In case of a cracked load-op, the load portion is sent to M", null));
		eventMap.put("RS_FULL_STALL.ALL", new PMUEvent(null, "0xCB", "0,1", "0x1f", "RS_FULL_STALL.ALL", "200003", "Counts the number of cycles the Alloc pipeline is stalled when any one of the RSs (IEC, FPC and MEC) is full. This event is a superset of all the individual RS stall event counts.", null));
		eventMap.put("INST_RETIRED.ANY_P", new PMUEvent("This event counts the number of instructions that retire execution. For instructions that consist of multiple micro-ops, this event counts the retirement of the last micro-op of the instruction. The counter continues counting during hardware interrupts, traps, and inside interrupt handlers.", "0xC0", "0,1", "0x0", "INST_RETIRED.ANY_P", "2000003", "Instructions retired", null));
		eventMap.put("CYCLES_DIV_BUSY.ALL", new PMUEvent("Cycles the divider is busy.This event counts the cycles when the divide unit is unable to accept a new divide UOP because it is busy processing a previously dispatched UOP. The cycles will be counted irrespective of whether or not another divide UOP is waiting to enter the divide unit (from the RS). This event might count cycles while a divide is in progress even if the RS is empty.  The divide instruction is one of the longest latency instructions in the machine.  Hence, it has a special event associated with it to help determine if divides are delaying the retirement of instructions.", "0xCD", "0,1", "0x1", "CYCLES_DIV_BUSY.ALL", "2000003", "Cycles the divider is busy.  Does not imply a stall waiting for the divider.", null));
		eventMap.put("INST_RETIRED.ANY", new PMUEvent("This event counts the number of instructions that retire.  For instructions that consist of multiple micro-ops, this event counts exactly once, as the last micro-op of the instruction retires.  The event continues counting while instructions retire, including during interrupt service routines caused by hardware interrupts, faults or traps.  Background: Modern microprocessors employ extensive pipelining and speculative techniques.  Since sometimes an instruction is started but never completed, the notion of \"retirement\" is introduced.  A retired instruction is one that commits its states. Or stated differently, an instruction might be abandoned at some point. No instruction is truly finished until it retires.  This counter measures the number of completed instructions.  The fixed event is INST_RETIRED.ANY and the programmable event is INST_RETIRED.ANY_P.", "0x00", "Fixed counter 1", "0x1", "INST_RETIRED.ANY", "2000003", "Fixed Counter: Counts the number of instructions retired", null));
		eventMap.put("CPU_CLK_UNHALTED.CORE", new PMUEvent("Counts the number of core cycles while the core is not in a halt state. The core enters the halt state when it is running the HLT instruction. This event is a component in many key event ratios.  The core frequency may change from time to time. For this reason this event may have a changing ratio with regards to time. In systems with a constant core frequency, this event can give you a measurement of the elapsed time while the core was not in halt state by dividing the event count by the core frequency. This event is architecturally defined and is a designated fixed counter.  CPU_CLK_UNHALTED.CORE and CPU_CLK_UNHALTED.CORE_P use the core frequency which may change from time to time.  CPU_CLK_UNHALTE.REF_TSC and CPU_CLK_UNHALTED.REF are not affected by core frequency changes but counts as if the core is running at the maximum frequency all the time.  The fixed events are CPU_CLK_UNHALTED.CORE and CPU_CLK_UNHALTED.REF_TSC and the programmable events are CPU_CLK_UNHALTED.CORE_P and CPU_CLK_UNHALTED.REF.", "0x00", "Fixed counter 2", "0x2", "CPU_CLK_UNHALTED.CORE", "2000003", "Fixed Counter: Counts the number of unhalted core clock cycles", null));
		eventMap.put("CPU_CLK_UNHALTED.REF_TSC", new PMUEvent("Counts the number of reference cycles while the core is not in a halt state. The core enters the halt state when it is running the HLT instruction. This event is a component in many key event ratios.  The core frequency may change from time. This event is not affected by core frequency changes but counts as if the core is running at the maximum frequency all the time.  Divide this event count by core frequency to determine the elapsed time while the core was not in halt state.  Divide this event count by core frequency to determine the elapsed time while the core was not in halt state.  This event is architecturally defined and is a designated fixed counter.  CPU_CLK_UNHALTED.CORE and CPU_CLK_UNHALTED.CORE_P use the core frequency which may change from time to time.  CPU_CLK_UNHALTE.REF_TSC and CPU_CLK_UNHALTED.REF are not affected by core frequency changes but counts as if the core is running at the maximum frequency all the time.  The fixed events are CPU_CLK_UNHALTED.CORE and CPU_CLK_UNHALTED.REF_TSC and the programmable events are CPU_CLK_UNHALTED.CORE_P and CPU_CLK_UNHALTED.REF.", "0x00", "Fixed counter 3", "0x3", "CPU_CLK_UNHALTED.REF_TSC", "2000003", "Fixed Counter: Counts the number of unhalted reference clock cycles", null));
		eventMap.put("CPU_CLK_UNHALTED.CORE_P", new PMUEvent("This event counts the number of core cycles while the core is not in a halt state. The core enters the halt state when it is running the HLT instruction. In mobile systems the core frequency may change from time to time. For this reason this event may have a changing ratio with regards to time.", "0x3C", "0,1", "0x0", "CPU_CLK_UNHALTED.CORE_P", "2000003", "Core cycles when core is not halted", null));
		eventMap.put("CPU_CLK_UNHALTED.REF", new PMUEvent("This event counts the number of reference cycles that the core is not in a halt state. The core enters the halt state when it is running the HLT instruction. In mobile systems the core frequency may change from time. This event is not affected by core frequency changes but counts as if the core is running at the maximum frequency all the time.", "0x3C", "0,1", "0x1", "CPU_CLK_UNHALTED.REF", "2000003", "Reference cycles when core is not halted", null));
		eventMap.put("BACLEARS.ALL", new PMUEvent("The BACLEARS event counts the number of times the front end is resteered, mainly when the Branch Prediction Unit cannot provide a correct prediction and this is corrected by the Branch Address Calculator at the front end.  The BACLEARS.ANY event counts the number of baclears for any type of branch.", "0xE6", "0,1", "0x1", "BACLEARS.ALL", "200003", "Counts the number of baclears", null));
		eventMap.put("BACLEARS.RETURN", new PMUEvent("The BACLEARS event counts the number of times the front end is resteered, mainly when the Branch Prediction Unit cannot provide a correct prediction and this is corrected by the Branch Address Calculator at the front end.  The BACLEARS.RETURN event counts the number of RETURN baclears.", "0xE6", "0,1", "0x8", "BACLEARS.RETURN", "200003", "Counts the number of RETURN baclears", null));
		eventMap.put("BACLEARS.COND", new PMUEvent("The BACLEARS event counts the number of times the front end is resteered, mainly when the Branch Prediction Unit cannot provide a correct prediction and this is corrected by the Branch Address Calculator at the front end.  The BACLEARS.COND event counts the number of JCC (Jump on Condtional Code) baclears.", "0xE6", "0,1", "0x10", "BACLEARS.COND", "200003", "Counts the number of JCC baclears", null));
		eventMap.put("BR_INST_RETIRED.ALL_TAKEN_BRANCHES", new PMUEvent("ALL_TAKEN_BRANCHES counts the number of all taken branch instructions retired.  Branch prediction predicts the branch target and enables the processor to begin executing instructions long before the branch true execution path is known. All branches utilize the branch prediction unit (BPU) for prediction. This unit predicts the target address not only based on the EIP of the branch but also based on the execution path through which execution reached this EIP. The BPU can efficiently predict the following branch types: conditional branches, direct calls and jumps, indirect calls and jumps, returns.", "0xC4", "0,1", "0x80", "BR_INST_RETIRED.ALL_TAKEN_BRANCHES", "200003", "Counts the number of taken branch instructions retired", null));
		eventMap.put("MEM_UOPS_RETIRED.DTLB_MISS_LOADS", new PMUEvent("This event counts the number of load ops retired that had DTLB miss.", "0x04", "0,1", "0x8", "MEM_UOPS_RETIRED.DTLB_MISS_LOADS", "200003", "Loads missed DTLB", null));
		eventMap.put("PAGE_WALKS.D_SIDE_WALKS", new PMUEvent("This event counts when a data (D) page walk is completed or started.  Since a page walk implies a TLB miss, the number of TLB misses can be counted by counting the number of pagewalks.", "0x05", "0,1", "0x1", "PAGE_WALKS.D_SIDE_WALKS", "100003", "D-side page-walks", null));
		eventMap.put("PAGE_WALKS.D_SIDE_CYCLES", new PMUEvent("This event counts every cycle when a D-side (walks due to a load) page walk is in progress. Page walk duration divided by number of page walks is the average duration of page-walks.", "0x05", "0,1", "0x1", "PAGE_WALKS.D_SIDE_CYCLES", "200003", "Duration of D-side page-walks in core cycles", null));
		eventMap.put("PAGE_WALKS.I_SIDE_WALKS", new PMUEvent("This event counts when an instruction (I) page walk is completed or started.  Since a page walk implies a TLB miss, the number of TLB misses can be counted by counting the number of pagewalks.", "0x05", "0,1", "0x2", "PAGE_WALKS.I_SIDE_WALKS", "100003", "I-side page-walks", null));
		eventMap.put("PAGE_WALKS.I_SIDE_CYCLES", new PMUEvent("This event counts every cycle when a I-side (walks due to an instruction fetch) page walk is in progress. Page walk duration divided by number of page walks is the average duration of page-walks.", "0x05", "0,1", "0x2", "PAGE_WALKS.I_SIDE_CYCLES", "200003", "Duration of I-side page-walks in core cycles", null));
		eventMap.put("PAGE_WALKS.WALKS", new PMUEvent("This event counts when a data (D) page walk or an instruction (I) page walk is completed or started.  Since a page walk implies a TLB miss, the number of TLB misses can be counted by counting the number of pagewalks.", "0x05", "0,1", "0x3", "PAGE_WALKS.WALKS", "100003", "Total page walks that are completed (I-side and D-side)", null));
		eventMap.put("PAGE_WALKS.CYCLES", new PMUEvent("This event counts every cycle when a data (D) page walk or instruction (I) page walk is in progress.  Since a pagewalk implies a TLB miss, the approximate cost of a TLB miss can be determined from this event.", "0x05", "0,1", "0x3", "PAGE_WALKS.CYCLES", "200003", "Total cycles for all the page walks. (I-side and D-side)", null));
    }

    public PMUEvent get(String eventName) {
        return eventMap.get(eventName.toUpperCase());
    }

	public void forEach(Consumer<PMUEvent> action) {
		for (PMUEvent event : eventMap.values())
			action.accept(event);
	}
}